stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.45.1-jammy
  script:
    - npm ci
    - npx playwright install
    - QASE_MODE=testops npx playwright test tests/example.spec.ts